CREATE DATABASE Filmes_Manha;
USE Filmes_Manha;

CREATE TABLE Filmes (
	IdFilmes INT PRIMARY KEY IDENTITY,
	Titulo	 VARCHAR(255)
);

CREATE TABLE Genero (
	IdGenero INT PRIMARY KEY IDENTITY,
	Nome	 VARCHAR(255)
)

CREATE TABLE Usuarios(
	IdUsuario INT IDENTITY PRIMARY KEY,
	Email VARCHAR (255) NOT NULL,
	Senha VARCHAR (255) NOT NULL,
	Permissao VARCHAR (255) NOT NULL UNIQUE
);

